@baseUrl = http://localhost/dwes/mvccomposer

### LISTAR
GET {{baseUrl}}/apicar/cars
Accept: application/json

###

### CREAR (POST)
POST http://localhost/mvcapi/apiarticulos/articulos
Content-Type: application/json
Accept: application/json

{
  "titulo": "Juan"
}

###

### VER 1
GET {{baseUrl}}/apicar/car/1
Accept: application/json

###

### ACTUALIZAR 1 (PUT)
PUT http://localhost/mvcapi/apiarticulos/articulo/3
Content-Type: application/json
Accept: application/json

{
  "titulo": "Pedro"
}

###

### BORRAR 1 (DELETE)
DELETE http://localhost/mvcapi/apiarticulos/articulo/2
Accept: application/json
